[app]
env = "local"
ip = "websocket-game"
host = "websocket-game"
port = ":6001"
site = "ws-game"

[pusher]
name = "遊戲中心"
ip = "sidecar"
host = "sidecar"
port = ":8501"
api_key = ""
max_link = 0
chat_room = "game"

    [pusher.rpc.register]
    service = "pusher"
    method = "Pusher.Register"

    [pusher.rpc.deregister]
    service = "pusher"
    method = "Pusher.Deregister"
